title: 'Ghada Almashaqbeh'
email: ghada.almashaqbeh at uconn.edu
tagline: 'Assistant Professor of Computer Science and Engineering <br/> University of Connecticut'
description: CSE - UConn
address: 'Office: ITEB 255 <br/> 371 Fairfield Way <br/> UBox 4155 <br/> Storrs, CT  06269'
quote: '"In theory, theory and practice are the same. In practice, they are not.” - Albert Einstein'
url: "http://ghadaalmashaqbeh.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed


exclude:
   - Gemfile
   - Gemfile.lock
