title: 'Ghada Almashaqbeh'
email: ghada at uconn.edu
tagline: 'Assistant Professor of Computer Science and Engineering <br/> University of Connecticut'
description: CSE - UConn
quote: '"In theory, theory and practice are the same. In practice, they are not.” - Albert Einstein'
url: "http://ghadaalmashaqbeh.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed


exclude:
   - Gemfile
   - Gemfile.lock
